name:                fwae-parser
version:             0.1.0.0
github:              "lmrjs/fwae-parser"
license:             BSD3
author:              "LMRJS"
maintainer:          ""
copyright:           "2018 Megha Singhania, Ryan Chen, Jonathan Chan, Samuel Or"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lmrjs/fwae-parser#readme>

dependencies:
- base >= 4.5 && < 4.10
- parsec
- hspec
- hspec-expectations
- groom
# - ghc-vis

library:
  source-dirs: src

executables:
  fwae-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fwae-parser

tests:
  fwae-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fwae-parser
